version: '3.0'

services:

    web:
        image: nginx:1-alpine
        volumes:
            - .:/srv
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build: ./docker
        volumes:
            - .:/srv
        environment:
            - APP_ENV

    db:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            PGUSER: postgres
            PGPASSWORD: postgres

    node:
        image: node:8.11-alpine
        volumes:
            - .:/srv
        working_dir: /srv
